a=float(input('введите первый катет a:'))
b=float(input('введите второй катет b:'))
c=(a ** 2 + b ** 2) ** 0.5
S=(a*b) * 0.5
P=a+b+c
c=str(c)
print('гипотенуза = ' + c)
S=str(S)
print('площадь треугольника = ' + S)
P=str(P)
print('периметр треугольника = '+ P)